-- ============================================================
-- PartnR — EF Core + ASP.NET Identity Schema
-- ============================================================
-- Run this in Supabase SQL Editor to create all tables
-- that the ASP.NET Core backend expects.
-- ============================================================

-- ============================================================
-- 1. ASP.NET Identity Tables (Guid keys)
-- ============================================================

CREATE TABLE "AspNetRoles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" uuid NOT NULL,
    "FirstName" character varying(50) NOT NULL DEFAULT '',
    "AvatarUrl" text,
    "City" character varying(100) NOT NULL DEFAULT '',
    "Bio" character varying(300) NOT NULL DEFAULT '',
    "FavoriteActivities" text[] NOT NULL DEFAULT '{}',
    "PhoneVerified" boolean NOT NULL DEFAULT false,
    "Role" character varying(10) NOT NULL DEFAULT 'user',
    "RatingAvg" numeric(3,2) NOT NULL DEFAULT 0,
    "RatingCount" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL DEFAULT false,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL DEFAULT false,
    "TwoFactorEnabled" boolean NOT NULL DEFAULT false,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL DEFAULT false,
    "AccessFailedCount" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

-- Identity indexes
CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName") WHERE "NormalizedName" IS NOT NULL;
CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName") WHERE "NormalizedUserName" IS NOT NULL;

-- ============================================================
-- 2. Domain Tables
-- ============================================================

CREATE TABLE "Activities" (
    "Id" uuid NOT NULL,
    "Name" character varying(50) NOT NULL,
    "Slug" character varying(50) NOT NULL,
    "Icon" character varying(10) NOT NULL DEFAULT '🏃',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_Activities" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Activities_Name" ON "Activities" ("Name");
CREATE UNIQUE INDEX "IX_Activities_Slug" ON "Activities" ("Slug");

CREATE TABLE "Events" (
    "Id" uuid NOT NULL,
    "CreatorId" uuid NOT NULL,
    "ActivityId" uuid NOT NULL,
    "Title" character varying(100) NOT NULL,
    "Description" character varying(1000) NOT NULL DEFAULT '',
    "City" character varying(100) NOT NULL,
    "Location" character varying(200) NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "MaxParticipants" integer NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'Published',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_Events" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Events_AspNetUsers_CreatorId" FOREIGN KEY ("CreatorId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Events_Activities_ActivityId" FOREIGN KEY ("ActivityId") REFERENCES "Activities" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Events_City_Date" ON "Events" ("City", "Date");
CREATE INDEX "IX_Events_ActivityId" ON "Events" ("ActivityId");
CREATE INDEX "IX_Events_Status" ON "Events" ("Status");

CREATE TABLE "EventParticipants" (
    "Id" uuid NOT NULL,
    "EventId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'Confirmed',
    "JoinedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_EventParticipants" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EventParticipants_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EventParticipants_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_EventParticipants_EventId_UserId" ON "EventParticipants" ("EventId", "UserId");

CREATE TABLE "Messages" (
    "Id" uuid NOT NULL,
    "EventId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Content" character varying(2000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Messages_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Messages_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Messages_EventId_CreatedAt" ON "Messages" ("EventId", "CreatedAt");

CREATE TABLE "Ratings" (
    "Id" uuid NOT NULL,
    "EventId" uuid NOT NULL,
    "RaterId" uuid NOT NULL,
    "RatedUserId" uuid NOT NULL,
    "Score" integer NOT NULL,
    "Comment" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_Ratings" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Rating_NotSelf" CHECK ("RaterId" != "RatedUserId"),
    CONSTRAINT "CK_Rating_Score" CHECK ("Score" >= 1 AND "Score" <= 5),
    CONSTRAINT "FK_Ratings_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Ratings_AspNetUsers_RaterId" FOREIGN KEY ("RaterId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Ratings_AspNetUsers_RatedUserId" FOREIGN KEY ("RatedUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_Ratings_EventId_RaterId_RatedUserId" ON "Ratings" ("EventId", "RaterId", "RatedUserId");
CREATE INDEX "IX_Ratings_RatedUserId" ON "Ratings" ("RatedUserId");

-- ============================================================
-- 3. EF Core Migrations History Table
-- ============================================================
-- This tells EF Core that the schema already exists
-- so EnsureCreated() won't try to recreate it.

CREATE TABLE "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- ============================================================
-- 4. Seed Data — Activities
-- ============================================================

INSERT INTO "Activities" ("Id", "Name", "Slug", "Icon", "CreatedAt") VALUES
    ('a1000000-0000-0000-0000-000000000001', 'Running', 'running', '🏃', now()),
    ('a1000000-0000-0000-0000-000000000002', 'Randonnée', 'randonnee', '🥾', now()),
    ('a1000000-0000-0000-0000-000000000003', 'Vélo', 'velo', '🚴', now()),
    ('a1000000-0000-0000-0000-000000000004', 'Jeux de société', 'jeux-de-societe', '🎲', now()),
    ('a1000000-0000-0000-0000-000000000005', 'Tennis', 'tennis', '🎾', now()),
    ('a1000000-0000-0000-0000-000000000006', 'Yoga', 'yoga', '🧘', now()),
    ('a1000000-0000-0000-0000-000000000007', 'Natation', 'natation', '🏊', now()),
    ('a1000000-0000-0000-0000-000000000008', 'Escalade', 'escalade', '🧗', now()),
    ('a1000000-0000-0000-0000-000000000009', 'Football', 'football', '⚽', now()),
    ('a1000000-0000-0000-0000-000000000010', 'Badminton', 'badminton', '🏸', now());
